### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by adammorphy** [UBC-MDS/DSCI_525_Group26#1]
**Tasks:**

- [x] Team Contract (Adam)

- [ ] Create Repo & Project Structure

- [ ] Download Data

- [ ] Combine to CSVs

- [ ] Load CSV to memory and complete simple EDA

- [ ] EDA in R

**Markdown Machine Comparison:**

| Team Member | Operating System | RAM | Processor | Is SSD | Time taken | |:-----------:|:----------------:|:---:|:---------:|:------:|:----------:| 
| Adam Morphy    |  MacOS Big Sur   |  8GB  |   1.8 GHz Dual-Core Intel Core i5   |  Yes   |            |
 | Mukund Iyer   |                  |     |           |        |            |
 | Julien Gordon   |                  |     |           |        |            |
 | Shiva Shankar Jena    |    MacOS Catalina 10.15.7      |  4GB   |      1.4 GHz Dual-Core Intel Core i5     |     Yes   |            |

**Comment by miyer26** [comment]
| Mukund Iyer | MacOS Monterey | 8GB | 1.4 GHz Quad-Core Intel Core i5 | Yes | |

**Comment by BooleanJulien** [comment]
| Julien Gordon | Ubuntu 20.04.4 LTS | 16GB | AMD® Ryzen 7 5800h with radeon graphics | Yes | |
